### ISSUE TITLE
Requirement.sh showing me there is no R installed but R is working.

### ISSUE THREAD

**Issue by awais4302** [collab-uniba/Senti4SD#13]
![Capture](https://user-images.githubusercontent.com/27438348/60011641-826f0080-967a-11e9-9dec-98778009eb8d.PNG)

**Comment by fedemaiorano** [comment]
Hi @awais4302. Try running ```which R``` in your shell. What is the result?

**Comment by awais4302** [comment]
result i get is /usr/bin/R

**Comment by fedemaiorano** [comment]
Maybe there's a problem with backticks. I updated the ```requirements.sh``` script. Try relaunching the new version and let me know if it works.

**Comment by awais4302** [comment]
![image](https://user-images.githubusercontent.com/27438348/60015602-31640a00-9684-11e9-9025-94983fd917e0.png)

Getting this error now.

**Comment by fedemaiorano** [comment]
You simply are not allowed to write to that folder. Run R as an administrator or configure R to use a different library path.

**Comment by awais4302** [comment]
yes Got it just find the link. Thanks !!
https://stackoverflow.com/questions/32540919/library-is-not-writable/45036570
