### ISSUE TITLE
Different sentiment results

### ISSUE THREAD

**Issue by IlyasAzeem** [collab-uniba/Senti4SD#8]
Hello! @bateman 
I ran Senti4SD on the statements given in the appendix section A, table B, of your paper titled: "Sentiment Polarity Detection for Software Development". I found that the tool assigns sentiment 'Neutral' which are labeled 'Negative' in Table B. 
What can be the reason? Why it label the statement incorrectly on which it has been trained.

**Comment by bateman** [comment]
Those are examples of manual annotations from the raters, not tool predictions
